Feature/authentication
ireland-advisor/Advisor pull request #14
Opened 2020-04-20 15:45 UTC by ireland-advisor

## Summary
* add oauth 2.0 for user to login through okta with okta html
* add unit/API test on users app, but haven't add test for oauth app
* add pipenv to manage the python environment, please consult "Other information" for usage
## Other information
To run this  repo successfully, you have to:

launch the environment:

`pipenv shell`

migrate the database:

`python3 manage.py migrate `

run the server:

`python3 manage.py runserver`

2020-04-20 18:02 UTC, gonac requested changes

2020-04-20 18:02 UTC, gonac commented on advisor_api/settings.py
> +CLIENT_SECRET = "FxrXdp5YBUdPdp3wyaE3Z6NMGMBGXGJN9S3UL1CU"
These(CLIENT_ID and CLIENT_SECRET  ) are sensitive values and the need to be kept secret

2020-04-20 18:02 UTC, gonac commented on advisor_api/settings.py
>  DEBUG = True
These should be false

2020-04-20 18:02 UTC, gonac commented on advisor_api/settings.py
> +REDIRECT_URI = "http://localhost:8000/oauth2/callback"
We cannot have localhost as redirect address

2020-04-22 17:56 UTC, ireland-advisor commented on advisor_api/settings.py
>  DEBUG = True
Updated

2020-04-22 17:58 UTC, ireland-advisor commented on advisor_api/settings.py
> +REDIRECT_URI = "http://localhost:8000/oauth2/callback"
These variables have been added to the env. file and won't be uploaded to GitHub 
Therefore, whoever is running it please create a .env file and run `source .env` command
plus, all the .idea files have been removed as well

2020-04-22 17:59 UTC, ireland-advisor commented
I have updated the info, move the sensitive info to local files. 
Whoever is using it please add to the .env source file

2020-04-23 19:26 UTC, gonac approved these changes

2020-04-23 19:26 UTC, merged